# Generated by Django 5.0.2 on 2024-03-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Book", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
