# Generated by Django 5.0.2 on 2024-03-03 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Book", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("staff", "Staff"),
                            ("member", "Member"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.CharField(max_length=17, primary_key=True, serialize=False),
                ),
                ("firstName", models.CharField(max_length=30)),
                ("lastName", models.CharField(max_length=30)),
                ("score", models.IntegerField(default=0)),
                ("address", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=12)),
                ("birthDate", models.DateField(blank=True, null=True)),
                ("email", models.EmailField(max_length=80)),
                ("password", models.CharField(max_length=128)),
                ("createDate", models.DateField()),
                (
                    "resetPasswordCode",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("builtIn", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name_plural": "Kullanıcılar",
            },
        ),
        migrations.CreateModel(
            name="Loan",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("loanDate", models.DateTimeField()),
                ("expireData", models.DateTimeField()),
                ("returnData", models.DateTimeField(blank=True, null=True)),
                ("notes", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "bookId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Book.books"
                    ),
                ),
                (
                    "userId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="User.user"
                    ),
                ),
            ],
        ),
    ]
