# Generated by Django 5.0.2 on 2024-03-04 13:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("User", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="score",
        ),
    ]
