# Generated by Django 5.0.2 on 2024-03-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("User", "0003_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(max_length=17),
        ),
    ]
